namespace: kinetix
dataset_id: ???
kwargs:
  batch_size: 256
  num_polygons: 5
  num_circles: 2
  num_joints: 1
  num_thrusters: 1
  frame_skip: 2
  observation: symbolic_entity
  shards: -1
  seed: 42
