# @package _global_

total_timesteps: 100_000_000

training:
  num_epochs: 20

environment:
  num_envs: 1024
  reset_ratio: 64

rollout:
  num_steps: 64

num_layers: 2

cell:
  features: 256
  dtype: bfloat16

network:
  dtype: bfloat16

algorithm:
  num_minibatches: 16
  update_epochs: 2
  clip_coefficient: 0.2
  clip_value_loss: True
  entropy_coefficient: 0.01
  value_coefficient: 2.0
  gamma: 0.99
  gae_lambda: 0.90

optimizer:
  name: muon
  lr: 0.005
  anneal: true
  alpha: 0.0
  max_grad_norm: 1.5
