# @package _global_

total_timesteps: 104_857_600

training:
  num_epochs: 20

environment:
  num_envs: 2048

rollout:
  num_steps: 64

num_layers: 2

cell:
  features: 256
  dtype: bfloat16

network:
  dtype: bfloat16

algorithm:
  num_minibatches: 16
  update_epochs: 1
  clip_coefficient: 0.2
  clip_value_loss: true
  entropy_coefficient: 0.001
  value_coefficient: 0.5
  gamma: 0.966
  gae_lambda: 0.95

optimizer:
  name: muon
  lr: 0.003
  max_grad_norm: 0.4
