# @package _global_

defaults:
  - override /hydra/sweeper: carbs

seed: ${hydra:job.num}

hydra:
  sweep:
    dir: sweeps/${hydra.runtime.choices.algorithm}/${hydra.runtime.choices.environment}/${now:%Y-%m-%d_%H-%M-%S}
