# @package _global_

total_timesteps: 20_000_000

environment:
  num_envs: 1024

rollout:
  num_steps: 32

algorithm:
  num_minibatches: 8
  update_epochs: 2
  gamma: 1.0
  gae_lambda: 0.95
  entropy_coefficient: 0.01

optimizer:
  lr: 3e-4
  max_grad_norm: 0.5

network:
  features: 256
  layers: 2

score: gauntlet/mean

artisans:
  gauntlet:
    _target_: boonta.artisans.Gauntlet
    opponents:
      random:
        _target_: boonta.environments.connectx.uniform
        _partial_: true
      negamax_1:
        _target_: boonta.environments.connectx.Negamax
        depth: 1
        rows: ${environment.kwargs.rows}
        columns: ${environment.kwargs.columns}
        inarow: ${environment.kwargs.inarow}
      negamax_2:
        _target_: boonta.environments.connectx.Negamax
        depth: 2
        rows: ${environment.kwargs.rows}
        columns: ${environment.kwargs.columns}
        inarow: ${environment.kwargs.inarow}
      negamax_4:
        _target_: boonta.environments.connectx.Negamax
        depth: 4
        rows: ${environment.kwargs.rows}
        columns: ${environment.kwargs.columns}
        inarow: ${environment.kwargs.inarow}
      negamax_6:
        _target_: boonta.environments.connectx.Negamax
        depth: 6
        rows: ${environment.kwargs.rows}
        columns: ${environment.kwargs.columns}
        inarow: ${environment.kwargs.inarow}
