import optax

from boonta.algorithms.recurrent_pupo import RecurrentPuPOConfig

from ..sections import Optimizer, Rollout
from ..store import builds, fbuilds
from . import algorithm, special

algorithm(
    dict(
        defaults=[{"/torso": "default"}, {"/cell": "min_gru"}, {"/stack": "highway"}],
        algorithm=fbuilds(
            RecurrentPuPOConfig,
            num_minibatches=8,
            update_epochs=4,
            clip_coefficient=0.2,
            clip_value_loss=True,
            entropy_coefficient=0.01,
            value_coefficient=0.5,
            gamma=0.99,
            gae_lambda=0.95,
            advantage_clip=1.0,
            trace_clip=1.0,
            priority_exponent=0.8,
            normalize_advantage=True,
        ),
        importance_exponent=builds(optax.constant_schedule, value=0.2),
        rollout=Rollout(num_steps=128),
        environment=dict(num_envs=64),
        optimizer=Optimizer(lr=2.5e-4, max_grad_norm=0.5),
    ),
    name="recurrent_pupo",
)

special(
    "recurrent_pupo",
    "ale/montezuma",
    total_timesteps=50_000_000,
    training=dict(num_epochs=50),
    environment=dict(num_envs=128),
    rollout=dict(num_steps=64),
    num_layers=2,
    cell=dict(features=256, dtype="bfloat16"),
    network=dict(dtype="bfloat16"),
    algorithm=dict(
        num_minibatches=8,
        update_epochs=2,
        clip_coefficient=0.2,
        clip_value_loss=True,
        entropy_coefficient=0.01,
        value_coefficient=2.0,
        gamma=0.999,
        gae_lambda=0.95,
    ),
    optimizer=dict(name="muon", lr=0.005, anneal=True, min_lr_ratio=0.0, max_grad_norm=1.5),
)
special(
    "recurrent_pupo",
    "craftax",
    total_timesteps=100_000_000,
    training=dict(num_epochs=20),
    environment=dict(num_envs=1024, reset_ratio=64),
    rollout=dict(num_steps=64),
    num_layers=2,
    cell=dict(features=256, dtype="bfloat16"),
    network=dict(dtype="bfloat16"),
    algorithm=dict(
        num_minibatches=16,
        update_epochs=2,
        clip_coefficient=0.2,
        clip_value_loss=True,
        entropy_coefficient=0.01,
        value_coefficient=2.0,
        gamma=0.99,
        gae_lambda=0.90,
    ),
    optimizer=dict(name="muon", lr=0.005, anneal=True, min_lr_ratio=0.0, max_grad_norm=1.5),
)
special(
    "recurrent_pupo",
    "gymnax/minatar",
    total_timesteps=104_857_600,
    training=dict(num_epochs=20),
    environment=dict(
        num_envs=8192,
        sticky_action_prob=0.1,
        kwargs=dict(use_minimal_action_set=False, params=dict(max_steps_in_episode=100000)),
    ),
    rollout=dict(num_steps=64),
    num_layers=2,
    cell=dict(features=256, dtype="bfloat16"),
    network=dict(encoder="linear", dtype="bfloat16"),
    algorithm=dict(
        num_minibatches=16,
        update_epochs=2,
        clip_coefficient=0.2,
        clip_value_loss=True,
        entropy_coefficient=0.01,
        value_coefficient=2.0,
        gamma=0.99,
        gae_lambda=0.90,
    ),
    optimizer=dict(name="muon", lr=0.015, anneal=True, max_grad_norm=1.5),
)
special(
    "recurrent_pupo",
    "jumanji/sokoban",
    total_timesteps=100_000_000,
    training=dict(num_epochs=50),
    environment=dict(num_envs=4096),
    rollout=dict(num_steps=64),
    num_layers=2,
    cell=dict(features=256, dtype="bfloat16"),
    network=dict(dtype="bfloat16"),
    algorithm=dict(
        num_minibatches=16,
        update_epochs=2,
        clip_coefficient=0.2,
        clip_value_loss=True,
        entropy_coefficient=0.01,
        value_coefficient=2.0,
        gamma=0.99,
        gae_lambda=0.90,
    ),
    optimizer=dict(name="muon", lr=0.005, anneal=True, min_lr_ratio=0.0, max_grad_norm=1.5),
)
special(
    "recurrent_pupo",
    "mapox/find_return",
    total_timesteps=1_500_000_000,
    training=dict(num_epochs=100),
    environment=dict(num_envs=2048, kwargs=dict(num_agents=8)),
    rollout=dict(num_steps=64),
    num_layers=2,
    cell=dict(features=256, dtype="bfloat16"),
    network=dict(dtype="bfloat16"),
    algorithm=dict(
        num_minibatches=16,
        update_epochs=1,
        clip_coefficient=0.2,
        clip_value_loss=True,
        entropy_coefficient=0.001,
        value_coefficient=0.5,
        gamma=0.966,
        gae_lambda=0.95,
    ),
    optimizer=dict(name="muon", lr=0.003, max_grad_norm=0.4),
)
special(
    "recurrent_pupo",
    "mapox",
    total_timesteps=104_857_600,
    training=dict(num_epochs=20),
    environment=dict(num_envs=2048),
    rollout=dict(num_steps=64),
    num_layers=2,
    cell=dict(features=256, dtype="bfloat16"),
    network=dict(dtype="bfloat16"),
    algorithm=dict(
        num_minibatches=16,
        update_epochs=1,
        clip_coefficient=0.2,
        clip_value_loss=True,
        entropy_coefficient=0.001,
        value_coefficient=0.5,
        gamma=0.966,
        gae_lambda=0.95,
    ),
    optimizer=dict(name="muon", lr=0.003, max_grad_norm=0.4),
)
