# @package _global_

buffer:
  _target_: boonta.buffers.make_prioritised_episode_buffer
  max_length: ${replay.capacity}
  min_length: ${buffer.sample_sequence_length}
  sample_batch_size: 256
  sample_sequence_length: ???
  add_batch_size: ${environment.num_envs}
  add_sequences: true
  priority_exponent: 0.6
