namespace: jaxued
suite: maze
env_id: Maze
kwargs:
  height: 13
  width: 13
  n_walls: 25
  agent_view_size: 5
  normalize_obs: true
  penalize_time: true
  max_steps_in_episode: 250
mutation:
  max_num_edits: 100
