namespace: kinetix
suite: kinetix
env_id:
  - s/h0_weak_thrust
  - s/h1_thrust_over_ball
  - s/h2_one_wheel_car
  - s/h3_point_the_thruster
  - s/h4_thrust_aim
  - s/h5_rotate_fall
  - s/h6_unicycle_right
  - s/h7_unicycle_left
  - s/h8_unicycle_balance
  - s/h9_explode_then_thrust_over
num_envs: 256
kwargs:
  action_type: multi_discrete
  observation_type: symbolic_entity
