# @package _global_

defaults:
  - /dataset: minari/mujoco/expert
  - override /podracer: quadinaros

algorithm:
  _target_: boonta.algorithms.bc.BCConfig
  batch_size: 256
  entropy_coefficient: 0.0

environment:
  num_envs: 32

optimizer:
  lr: 3e-4
