# @package _global_

algorithm:
  _target_: boonta.algorithms.cispo.CISPOConfig
  group_size: 8
  num_minibatches: 16
  update_epochs: 2
  epsilon_low: 1.0
  epsilon_high: 0.2
  kl_coefficient: 0.0
  gamma: 0.99

rollout:
  num_steps: 256

environment:
  num_envs: 512

optimizer:
  lr: 2.5e-4
  max_grad_norm: 0.5
