# @package _global_

algorithm:
  _target_: boonta.algorithms.ppo.PPOConfig
  num_minibatches: 16
  update_epochs: 2
  clip_coefficient: 0.2
  clip_value_loss: True
  entropy_coefficient: 0.01
  value_coefficient: 0.5
  gamma: 0.99
  gae_lambda: 0.95
  normalize_advantage: False

rollout:
  num_steps: 16

environment:
  num_envs: 4096

optimizer:
  lr: 2.5e-4
  max_grad_norm: 0.5
