# @package _global_

algorithm:
  _target_: boonta.algorithms.pqn.PQNConfig
  num_minibatches: 4
  update_epochs: 1
  gamma: 0.99
  q_lambda: 0.65

rollout:
  num_steps: 16

environment:
  num_envs: 128

optimizer:
  lr: 5e-4
  max_grad_norm: 10.0

exploration:
  start: 1.0
  end: 0.01
  fraction: 0.2
