# @package _global_

algorithm:
  _target_: boonta.algorithms.recurrent_cispo.RecurrentCISPOConfig
  group_size: 8
  num_minibatches: 16
  update_epochs: 2
  epsilon_low: 1.0
  epsilon_high: 0.2
  kl_coefficient: 0.0
  gamma: 1.0

rollout:
  num_steps: 30

environment:
  num_envs: 128

optimizer:
  lr: 1e-5
  max_grad_norm: 0.5
