# @package _global_

defaults:
  - /torso: default
  - /cell: gru
  - /stack: default

algorithm:
  _target_: boonta.algorithms.recurrent_ppo.RecurrentPPOConfig
  num_minibatches: 8
  update_epochs: 4
  clip_coefficient: 0.2
  clip_value_loss: True
  entropy_coefficient: 0.01
  value_coefficient: 0.5
  gamma: 0.99
  gae_lambda: 0.95
  normalize_advantage: False

rollout:
  num_steps: 128

environment:
  num_envs: 64

optimizer:
  lr: 2.5e-4
  max_grad_norm: 0.5
