# @package _global_

defaults:
  - /torso: default
  - /cell: gru
  - /stack: default
  - /buffer: trajectory

algorithm:
  _target_: boonta.algorithms.recurrent_dqn.RecurrentDQNConfig
  updates_per_step: 32
  gamma: 0.99
  tau: 0.005

rollout:
  num_steps: 1

environment:
  num_envs: 128

replay:
  capacity: 262_144

optimizer:
  lr: 5e-4
  max_grad_norm: 10.0

exploration:
  start: 1.0
  end: 0.01
  fraction: 0.2
