_target_: boonta.curricula.accel
_partial_: true
capacity: 4000
replay_probability: 0.5
staleness: 0.3
temperature: 1.0
minimum_fill: 0.5
robust: false
num_edits: 5
gamma: ${algorithm.gamma}
gae_lambda: ${algorithm.gae_lambda}
sample: ???
mutate: ???
score:
  _target_: boonta.curricula.maximum_monte_carlo
  _partial_: true
