# @package _global_

algorithm:
  num_minibatches: 4
  update_epochs: 5
  clip_coefficient: 0.2
  clip_value_loss: true
  entropy_coefficient: 0.005
  value_coefficient: 1.0
  gamma: 0.99
  gae_lambda: 0.95
  normalize_advantage: True

rollout:
  num_steps: 24

optimizer:
  lr: 1.0e-3
  max_grad_norm: 1.0

total_timesteps: 150_000_000
