# @package _global_

total_timesteps: 200_000_000

algorithm:
  gamma: 1.0
  gae_lambda: 0.97
  num_minibatches: 1
  update_epochs: 2
  clip_coefficient: 0.2
  clip_value_loss: True
  entropy_coefficient: 0.003
  value_coefficient: 0.5
  normalize_advantage: True

rollout:
  num_steps: 64

evaluation:
  num_steps: 719

environment:
  num_envs: 512

network:
  features: 96
  blocks: 4
  market_none_bias: 11.0
  pretrained: null
  anchor_coefficient: 0.0

optimizer:
  lr: 3.0e-4
  max_grad_norm: 0.5
