# @package _global_
defaults:
  - /hyperparameters/recurrent_ppo/jaxued/maze
  - _self_

curriculum:
  replay_probability: 0.8
  temperature: 0.3
  robust: true
  sample:
    _target_: boonta.environments.jaxued.maze_generator
    height: ${environment.kwargs.height}
    width: ${environment.kwargs.width}
    n_walls: ${environment.kwargs.n_walls}
  mutate:
    _target_: boonta.environments.jaxued.maze_mutator
    max_num_edits: 100
