defaults:
  - pbt_schema
  - _self_

generation: early_stopping.at
checkpoint: checkpoint
num_epochs: ${training.num_epochs}
overrides:
  - early_stopping=epochs
  - scoring=final
  - +artisan@artisans.checkpointer=checkpointer
  - +logger@loggers.orbax=orbax
  - ++loggers.orbax.max_to_keep=1
  - ++loggers.orbax.best=false
