total_timesteps: 5_000_000
seed: 0

training:
  num_epochs: 10

evaluation:
  num_steps: 0

score: ${eval:'"evaluation" if ${evaluation.num_steps} else "training"'}/episode_return

loggers: {}
artisans: {}

defaults:
  - _self_
  - podracer: anakin
  - algorithm: ppo
  - environment: gymnax/minatar/breakout
  - logger: dashboard
  - optional hyperparameters: ${cascading_fallback:hyperparameters,${algorithm},${environment}}
  - curriculum: default
  - scoring: best

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${oc.env:SLURM_ARRAY_TASK_ID,0}
