total_timesteps: 5_000_000
seed: ${trial:}
num_processes: 1
checkpoint: null
save: null

training:
  num_epochs: 10

evaluation:
  num_steps: 0

score: ${eval:'"evaluation" if ${evaluation.num_steps} else "training"'}/episode_return

loggers: {}
artisans: {}

defaults:
  - _self_
  - podracer: anakin
  - algorithm: ppo
  - environment: gymnax/minatar/breakout
  - logger: dashboard
  - curriculum: default
  - optional hyperparameters: ${cascade:hyperparameters,${algorithm},${environment},${curriculum}}
  - scoring: best
  - early_stopping: default
  - optional search_space: ${cascade:search_space,${algorithm},${environment}}

hydra:
  run:
    dir: outputs/${oc.env:SLURM_JOB_ID,${now:%Y-%m-%d}/${now:%H-%M-%S}}-${oc.env:SLURM_ARRAY_TASK_ID,0}
  sweep:
    dir: sweeps/${hydra.runtime.choices.algorithm}/${hydra.runtime.choices.environment}/${now:%Y-%m-%d_%H-%M-%S}
