_target_: boonta.podracers.quadinaros.make
_partial_: true
config:
  _target_: boonta.podracers.quadinaros.QuadinarosConfig
  num_envs: ${environment.num_envs}
  batch_shape:
    - ${algorithm.batch_size}
  mesh:
    _target_: boonta.utils.mesh
    count: 1
